# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 275)
        Form.setMaximumSize(QtCore.QSize(380, 275))
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 380, 275))
        self.tabWidget.setMaximumSize(QtCore.QSize(380, 275))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_xyw = QtWidgets.QWidget()
        self.tab_xyw.setObjectName("tab_xyw")
        self.checkBox_jzmm = QtWidgets.QCheckBox(self.tab_xyw)
        self.checkBox_jzmm.setGeometry(QtCore.QRect(130, 150, 71, 16))
        self.checkBox_jzmm.setObjectName("checkBox_jzmm")
        self.checkBox_zddl = QtWidgets.QCheckBox(self.tab_xyw)
        self.checkBox_zddl.setGeometry(QtCore.QRect(220, 150, 71, 16))
        self.checkBox_zddl.setObjectName("checkBox_zddl")
        self.pushButton_ljwl = QtWidgets.QPushButton(self.tab_xyw)
        self.pushButton_ljwl.setGeometry(QtCore.QRect(50, 190, 75, 23))
        self.pushButton_ljwl.setObjectName("pushButton_ljwl")
        self.pushButton_dklj = QtWidgets.QPushButton(self.tab_xyw)
        self.pushButton_dklj.setGeometry(QtCore.QRect(160, 190, 75, 23))
        self.pushButton_dklj.setObjectName("pushButton_dklj")
        self.pushButton_dkqb = QtWidgets.QPushButton(self.tab_xyw)
        self.pushButton_dkqb.setGeometry(QtCore.QRect(270, 190, 75, 23))
        self.pushButton_dkqb.setObjectName("pushButton_dkqb")
        self.label_xywzh = QtWidgets.QLabel(self.tab_xyw)
        self.label_xywzh.setGeometry(QtCore.QRect(43, 40, 61, 20))
        self.label_xywzh.setObjectName("label_xywzh")
        self.label_xywmm = QtWidgets.QLabel(self.tab_xyw)
        self.label_xywmm.setGeometry(QtCore.QRect(43, 100, 61, 20))
        self.label_xywmm.setObjectName("label_xywmm")
        self.lineEdit_xywzh = QtWidgets.QLineEdit(self.tab_xyw)
        self.lineEdit_xywzh.setGeometry(QtCore.QRect(130, 30, 158, 31))
        self.lineEdit_xywzh.setObjectName("lineEdit_xywzh")
        self.lineEdit_xywmm = QtWidgets.QLineEdit(self.tab_xyw)
        self.lineEdit_xywmm.setGeometry(QtCore.QRect(130, 90, 158, 31))
        self.lineEdit_xywmm.setObjectName("lineEdit_xywmm")
        self.tabWidget.addTab(self.tab_xyw, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_wfmc = QtWidgets.QLabel(self.tab_4)
        self.label_wfmc.setGeometry(QtCore.QRect(43, 40, 61, 20))
        self.label_wfmc.setObjectName("label_wfmc")
        self.checkBox_zdkq = QtWidgets.QCheckBox(self.tab_4)
        self.checkBox_zdkq.setGeometry(QtCore.QRect(130, 150, 121, 16))
        self.checkBox_zdkq.setObjectName("checkBox_zdkq")
        self.label_wfmm = QtWidgets.QLabel(self.tab_4)
        self.label_wfmm.setGeometry(QtCore.QRect(43, 100, 61, 20))
        self.label_wfmm.setObjectName("label_wfmm")
        self.pushButton_gbwf = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_gbwf.setGeometry(QtCore.QRect(240, 190, 75, 23))
        self.pushButton_gbwf.setObjectName("pushButton_gbwf")
        self.pushButton_kqwf = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_kqwf.setGeometry(QtCore.QRect(130, 190, 75, 23))
        self.pushButton_kqwf.setObjectName("pushButton_kqwf")
        self.lineEdit_wfmc = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_wfmc.setGeometry(QtCore.QRect(130, 30, 158, 31))
        self.lineEdit_wfmc.setObjectName("lineEdit_wfmc")
        self.lineEdit_wfmm = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_wfmm.setGeometry(QtCore.QRect(130, 90, 158, 31))
        self.lineEdit_wfmm.setObjectName("lineEdit_wfmm")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.timeEdit = QtWidgets.QTimeEdit(self.tab_5)
        self.timeEdit.setGeometry(QtCore.QRect(140, 110, 71, 22))
        self.timeEdit.setObjectName("timeEdit")
        self.label_dsgj = QtWidgets.QLabel(self.tab_5)
        self.label_dsgj.setGeometry(QtCore.QRect(143, 50, 61, 20))
        self.label_dsgj.setObjectName("label_dsgj")
        self.tabWidget.addTab(self.tab_5, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBox_jzmm.setText(_translate("Form", "CheckBox"))
        self.checkBox_zddl.setText(_translate("Form", "CheckBox"))
        self.pushButton_ljwl.setText(_translate("Form", "PushButton"))
        self.pushButton_dklj.setText(_translate("Form", "PushButton"))
        self.pushButton_dkqb.setText(_translate("Form", "PushButton"))
        self.label_xywzh.setText(_translate("Form", "TextLabel"))
        self.label_xywmm.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_xyw), _translate("Form", "页"))
        self.label_wfmc.setText(_translate("Form", "TextLabel"))
        self.checkBox_zdkq.setText(_translate("Form", "CheckBox"))
        self.label_wfmm.setText(_translate("Form", "TextLabel"))
        self.pushButton_gbwf.setText(_translate("Form", "PushButton"))
        self.pushButton_kqwf.setText(_translate("Form", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "页"))
        self.label_dsgj.setText(_translate("Form", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Form", "页"))

